name: 'Surge.sh Teardown'
description: 'Teardown Surge.sh projects that match a regex'
branding:
  icon: 'archive'
  color: 'green'
inputs:
  regex:
    description: 'Regex string'
    required: true
    default: "[2-9]+ months ago"
  dryrun:
    description: 'Output Actions instead of applying them'
    default: false
runs:
  using: 'node20'
  main: 'dist/index.js'
