name: "Release"
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.SYNCED_GITHUB_TOKEN }}
          ref: "master"
      - name: Keep dist up-to-date
        run: |
          npm ci
          npm run build
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add dist/index.js
          git commit -m "chore: publish dist" || echo "nothing to commit"
          git push origin master
      - uses: actions/checkout@v4
        with:
          ref: master
      - name: Test Action
        uses: ./
        with:
          regex: "ago"
          dryrun: true
        env:
          SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
          SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: master
      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        with:
          extra_plugins: |
            "@semantic-release/commit-analyzer"
            "@semantic-release/release-notes-generator"
            "@semantic-release/git
            "@semantic-release/github
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
